Linux script for create icns
NiklasEi/bevy_game_template pull request #108
Opened 2024-03-10 18:39 UTC by Fidius-jko

#### Resizing icons and creating an icns file in Linux!

2024-03-13 14:29 UTC, NiklasEi requested changes
Thanks, this will be a big help for all users without a mac.

Can you mark the script as executable, please?

2024-03-13 14:29 UTC, NiklasEi commented on build/macos/create_icns_linux.sh
> +magick ../icon_1024x1024.png -resize 16x16    AppIcon.iconset/icon_16x16.png
I need to use `convert` here instead of `magick`

2024-03-13 14:29 UTC, NiklasEi commented on build/macos/create_icns_linux.sh
> +png2icns ./AppIcon.icns AppIcon.iconset/icon_16x16.png AppIcon.iconset/icon_32x32.png AppIcon.iconset/icon_128x128.png AppIcon.iconset/icon_256x256.png AppIcon.iconset/icon_512x512.png
Will this automatically use all the `@2x` files?

2024-03-17 09:42 UTC, Fidius-jko commented
> Can you mark the script as executable, please?

The file appears to be executable.
I don't understand how to fix this

2024-03-20 23:09 UTC, NiklasEi commented
> > Can you mark the script as executable, please?
> 
> The file appears to be executable. I don't understand how to fix this

I had to run `chmod +x create_icns_linux.sh` to be able to execute it and that command created a git diff. But if it is already executable on your end we can just merge this and I can verify later.

2024-03-21 09:09 UTC, Fidius-jko commented
I understood why it works for me. Because my folder is on a partition formatted in NTFS. I fixed this.

2024-03-21 19:27 UTC, NiklasEi approved these changes
Thank you :)

2024-03-21 19:27 UTC, merged